# Generated by Django 5.1.2 on 2024-10-25 18:02

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuineaPig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the guinea pig', max_length=50)),
                ('birth_year', models.PositiveIntegerField(help_text='Birth year of the guinea pig')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Image of the guinea pig', max_length=255, null=True, verbose_name='image')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Gender of the guinea pig', max_length=1)),
                ('adopted', models.BooleanField(default=False, help_text='Adoption status')),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(help_text="Adopter's contact number", max_length=15)),
                ('address', models.TextField(help_text="Adopter's address")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(auto_now_add=True, help_text='Date of adoption')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='adoptions.adopter')),
                ('guinea_pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='adoptions.guineapig')),
            ],
            options={
                'unique_together': {('guinea_pig', 'adopter')},
            },
        ),
    ]
