# Generated by Django 5.1.2 on 2024-10-26 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='adoption_date',
        ),
        migrations.AddField(
            model_name='adoption',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='adoption',
            name='living_arrangement',
            field=models.CharField(choices=[('flat', 'Flat'), ('house', 'House')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='adoption',
            name='number_of_guinea_pigs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adoption',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='guinea_pig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.guineapig'),
        ),
    ]
