# Generated by Django 5.1.2 on 2024-10-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_remove_adoption_adoption_date_adoption_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adopter',
        ),
    ]
