# Generated by Django 5.1.2 on 2024-11-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_alter_adoption_unique_together_adoption_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='number_of_guinea_pigs',
        ),
    ]
