# Generated by Django 5.1.2 on 2024-11-22 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0006_adoption_number_of_guinea_pigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='number_of_guinea_pigs',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
